# 定义客户端
co:
  spring:
    cloud:
      gateway:
        principals:
          - id: "239b7f7015414154a2fd5d315950731c"
            name: "手机端"
            secret: "123"
            owner: "client-app"
