spring:
  profiles:
    include: client,http-bin

# spring-cloud-config 相关配置
  cloud:
    config:
      uri: http://localhost:8888

# 设置端口为 80
server:
  port: 80


# 插件相关配置
co:
  spring:
    cloud:
      gateway:
        # 开启测试支持
        support-test-stage: true

