co:
  spring:
    cloud:
      gateway:
        routes:
          - id: 6e758e71f1534fd1a1c91b5187a2e091
            uri: http://www.baidu.com
            predicates:
              - name: Path
                args:
                  pattern: "/**"
            filters:
              - name: CoDefaultAuthentication
              - name: CoDefaultAuthorization
                args:
                  authorized-principal-set:
                    - APP
