co:
  spring:
    cloud:
      gateway:
        routes:
          - id: 5d50b843d00d4d339f5d8ffd60c95b34
            uri: http://httpbin.org
            predicates:
              - Path=/get
          - id: 7dad8a95cd9d45c69a9ca356ef06f148
            uri: http://httpbin.org
            predicates:
              - Path=/anything/**
            filters:
              - name: CoDefaultAuthentication
              - name: CoDefaultAuthorization
                args:
                  authorized-principal-set:
                    - APP
