co:
  spring:
    cloud:
      gateway:
        routes:
        - id: "7dad8a95cd9d45c69a9ca356ef06f148"
          uri: "http://httpbin.org"
          name: null
          doc-link: null
          predicates:
          - name: "Path"
            args:
              pattern: "/anything/**"
          filters: []
